"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var userController_1 = require("./userController");
var router = express_1.default.Router();
router.get('/users', userController_1.getUsers);
router.get('/users/:id', userController_1.getUserById);
router.get('/users/name/:name', userController_1.getUserByName);
router.post('/users', userController_1.createUser);
router.put('/users/:id', userController_1.updateUser);
router.delete('/users/:id', userController_1.deleteUser);
exports.default = router;
